openapi: 3.0.1

info:
  title: LumaTax API
  version: 1.0.0
  contact:
    name: Michael Mills
    email: m2mills@gmail.com

servers:
  - url: 'http://localhost:8080'
    description: dev

paths:
  /sales/transactions/file:
    post:
      summary: Upload sales transactions file
      operationId: uploadFile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesTransactionsSummary'
#        '400':
#          description: Illegal Argument Error
#        '500':
#          description: Internal Server Error
components:
  schemas:
    SalesTransactionsSummary:
      type: object
      properties:
        validRows:
          type: integer
          format: int32
        invalidRows:
          type: integer
          format: int32
        dateRange:
          type: string
        totalSales:
          type: number
          format: float
        totalTax:
          type: number
          format: float