server:
  port: 8082

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3309/pharma?autoReconnect=true&&useSSL=false
#    username: mmills
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    continue-on-error: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

security:
  cors:
    allowedOrigins: "*"